### ISSUE TITLE
how does this project compare with the official MHE archive?

### ISSUE THREAD

**Issue by ahcyip** [vikjam/mostly-harmless-replication#7]
https://economics.mit.edu/faculty/angrist/data1/mhe

**Comment by vikjam** [comment]
Hi Arthur,

I think the MHE is great and it is what makes this project possible! My primary motivation was to see if I could replace Stata with either R, Python, or Julia in my workflow, so I tried to replicate MHE in each of these languages. MHE mostly includes just Stata examples (and at least one SAS example).

**Comment by ptoche** [comment]
And it's a very worthwhile endeavor! how about adding that explanation to the readme?
